<a href="https://colab.research.google.com/github/Saadkhalid913/ML-Practice/blob/main/NUMPY_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''

  lesson 11 numpy neural network from scratch

'''

# imports 
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_blobs, make_moons

In [ ]:
# preparing non-linear dataset 
x , y = make_moons(n_samples=10, shuffle=True, noise=0.15)

n_samples = len(x)
input_neurons = 2
output_neurons = 2
learning_rate = 0.001 
Lambda = 0.01 

class NN():
  def __init__(self, input_neurons, output_neurons, lr):
    self.layer1 = np.random.rand(input_neurons, 3)
    self.layer2 = np.random.rand(3, output_neurons)
  
  def relu(self, x: np.array):
   return np.where(x > 0, x, 0)

  def sigmoid(self, x: np.array):
    return 1 / 1 - np.exp(-x)

  def Forward(self, x):
    out = np.dot(x, self.layer1)
    out = self.sigmoid(out)
    out = np.dot(out, self.layer2)
    return out 


n = NN(input_neurons=input_neurons, output_neurons=output_neurons, lr = learning_rate)
print(n.Forward(x))


[[ 0.21744223  0.71489291]
 [-0.17128952 -0.12714078]
 [ 0.38705416  0.97407079]
 [ 0.29268398  0.74783864]
 [-0.10793901 -0.19546025]
 [ 0.1699798   0.3950837 ]
 [ 0.18884588  0.63820079]
 [-0.12500223 -0.66345952]
 [ 0.05603884 -0.00981666]
 [ 0.27109403  0.65822018]]


In [ ]:
v = np.array([[1,1,1], 
              [1,1,1]])

m = np.array([[1,2,3], 
              [1,2,3], 
              [1,2,3]])
print(np.dot(v,m))

[[3 6 9]
 [3 6 9]]


In [ ]:
 def relu(x: np.array):
   return np.where(x > 0, x, 0)
