<a href="https://colab.research.google.com/github/Saadkhalid913/ML-Practice/blob/main/NUMPY_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''

  lesson 11 numpy neural network from scratch

'''

# imports 
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_blobs, make_moons

In [ ]:
# preparing non-linear dataset 
x , y = make_moons(n_samples=10, shuffle=True, noise=0.15)

In [ ]:


def relu(x: np.array):
   return np.where(x > 0, x, 0)

def retrieve(model):
  W1 = model["W1"]
  b1 = model["b1"]
  W2 = model["W2"]
  b2 = model["b2"]


  return W1, b1, W2, b2   
n_samples = len(x)
input_neurons = 2
output_neurons = 2
learning_rate = 0.001 
Lambda = 0.01 

# model_dict = {"W1": W1, "b1": b1, "W2": W2, "b2": b2}

def forward(x, model):
  W1, b1, W2, b2 = retrieve(model)
  
  out1 = x.dot(W1) + b1
  out1 = np.tanh(out1)
  out2 = out1.dot(W2) + b2
  out2 = np.tanh(out2)
  
  result = np.exp(out2)
  softmax = result / np.sum(result, axis = 1, keepdims=true)

  return softmax 

def loss(y_pred, y, model):
  W1, b1, W2, b2 = retrieve(model)
  confidence_array = np.zeros(y.shape[0])
  for i, correct_index in enumerate(y):
    confidence_array[i] = y_pred[i][correct_index]

  log_loss = np.sum(-np.log(confidence_array))
  reg_loss = (Lambda/2) * (np.sum(np.square(W1)) +np.sum(np.square(W1)))
  loss = log_loss + reg_loss 
  return float(loss / y.shape[0])

def predict(x):
  W1, b1, W2, b2 = retrieve(model)
  
  out1 = x.dot(W1) + b1
  out1 = np.tanh(out1)
  out2 = out1.dot(W2) + b2
  out2 = np.tanh(out2)
  
  result = np.exp(out2)
  softmax = result / np.sum(result, axis = 1, keepdims=true)

  return np.argmax(softmax, axis=1, keepdims=True) 

loss(np.random.rand(10,2), y, "")




[[0.         0.30022201 0.30022201 0.89708159]
 [1.         0.06639183 0.65486901 0.06639183]
 [1.         0.0124803  0.29919487 0.0124803 ]
 [1.         0.87514844 0.99037261 0.87514844]
 [0.         0.76391226 0.76391226 0.77004334]
 [0.         0.31157161 0.31157161 0.22457438]
 [0.         0.13574403 0.13574403 0.89831795]
 [1.         0.03719339 0.46200736 0.03719339]
 [1.         0.79685796 0.92232355 0.79685796]
 [0.         0.29149643 0.29149643 0.07366317]]


In [ ]:
ˇ

AttributeError: ignored